version: '3.3'
services:
  db:
    image: mysql:latest
    ports:
      - "33060:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_DATABASE=docker_demo_db
      - MYSQL_ROOT_PASSWORD=example

  deocker-demo:
    image: radostind/docker-demo:v1
    depends_on: [db]
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root